### PR TITLE
Modeling users

### PR DESCRIPTION
**Pull request by ngoquangthang154**
ready

### CODE REVIEW

**Comment by ngoquangthang154** [comment]
ready

**Comment by thangtx88** [comment]
3 commits

**Comment by thangtx88** [comment]
commented

**Comment by ngoquangthang154** [comment]
ready

**Comment by thangtx88** [comment]
4 commits

**Comment by thangtx88** [comment]
commented

**Comment by ngoquangthang154** [comment]
ready

**Comment by huongnguyenmta** [comment]
commented
Pull có 4 commit, bạn gộp commit lại nhé ;)

**Pull request closed without merging**
